---
# e-Science Central
# Copyright (C) 2008-2015 School of Computing Science, Newcastle University
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation at:
# http://www.gnu.org/licenses/gpl-2.0.html
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, 5th Floor, Boston, MA 02110-1301, USA.

#### Docs back-references:
#### /deployment/ansible/README.md

#
# The ear file of the performance and provenance monitoring server.
#
#performance_monitoring_ear: code/applications/monitorserver/ear/target/monitor.ear
# Location of the performance monitor ear file
#
#performance_monitor_dist_dir: ../../code/applications/monitorserver/ear/target/
performance_monitor_dist_dir: ../../../../../code/applications/monitorserver/ear/target/

#
# Location of the jboss package
#
jboss_dist_dir: ../../../../../documentation/buildAndInstall

#
# Location of the e-SC ear file
#
inkspot_dist_dir: ../../../../../code/server/Ear/target

#
# The current version of the server code.
# [TODO] This is not currently used. Needed for the integration with CI
#
version: 3.1-SNAPSHOT

# The port on which the database server runs.
# [TODO] This should be taken from the db-init/db roles
#
# Note that database server address is taken from the inventory
db_server_port: 5432

# This is the name of the server as published by the RMI registry.
# The name should be visible from engine machines
server_port: 8080

#
# Target location where jBoss AS code will be placed
#
jboss_home_dir: /usr/local/jboss-as-7.1.3

#
# Name of the OS user name under which jBoss AS will run
#
jboss_user: esc-srv

# These variables define organisation which will be registered during first start of the e-SC server
# Please DO EDIT them.
# Note that some of these may be overridden in the playbook, e.g. server-standalone.yml
RegInfo_OrganisationName: "e-Science Central" 
RegInfo_FirstName: ""
RegInfo_LastName: ""
RegInfo_UserName: ""
RegInfo_Password: ""
#RegInfo_GmailUser: ""
#RegInfo_GmailPassword: ""
#RegInfo_AdminGroup: Admins
#RegInfo_UserGroup: Users
RegInfo_StorageFolder: /mnt/server/orgdata
#RegInfo_AWSAccessKey: ""
#RegInfo_AWSSecretKey: ""
#RegInfo_AWSDomainName: ""
#RegInfo_AWSGlacierVaultName: ""

